### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by Axkaban** [pignatarig/vidbits#1]
Thank you for the frequent comments!
[https://github.com/pignatarig/vidbits/blob/master/app.js#L27](https://github.com/pignatarig/vidbits/blob/master/app.js#L27)

Great routes. Something you might like to use is creating middlewear for recurring code like the validation and build of the videos as well as finding the videos, you can create two functions that you call in as you need:

```
const findVideo = async (request) => {
  const {id} = request.params;

  return await Video.findOne({ _id: id });
}

const buildVideo = (video, {title, description, url}) => {
  video.title = title;
  video.description = description;
  video.url = url;

  video.validateSync();
};
```
Great work on the tests, I like to see the decisions and changes with commented out code:
[https://github.com/pignatarig/vidbits/blob/master/test/routes/videos-test.js#L18-L20](https://github.com/pignatarig/vidbits/blob/master/test/routes/videos-test.js#L18-L20)

does not mean that you should leave it there, but for this purpose it gives me a better idea of the places where you might have given more attention to for one reason or another.

Overall a 200 OK Pass!

**Comment by pignatarig** [comment]
Great you are right I was in kind of a rush so i missed one last refactoring but the deadline was there.

Thanks for your feedback
